apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: michael-persistent 
  namespace: aria-world
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi